AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  ExtraDetails: true
  Exclude:
    - bin/*
  TargetRubyVersion: 2.4

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
